# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:  
      #- name: Esegui i test
      #  run: python -m unittest discover -s tests/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Creazione di token.py
      #  run: echo "TELEGRAM_TOKEN = '$(echo ${{ secrets.TELEGRAM_TOKEN }})'" > src/token.py
      #  
      #- name: Creazione di token.txt
      #  run: echo "TELEGRAM_TOKEN = '$(echo ${{ secrets.TELEGRAM_TOKEN }})'" > src/token.txt
      #  
      #- name: Creazione di token1.txt
      #  run: echo "TELEGRAM_TOKEN = '$(echo ${{ secrets.TELEGRAM_TOKEN }})'" > src/token1.txt
        
     
      #- name: Rimozione filse sensibili
      #  run: rm -rf src/token.py src/token.txt

        
      #- name: Esegui il tuo script Python
      #  run: python ufferellox-ale.py
